# Source of truth for server/server.properties. Local test server only - never expose this to the internet.
# online-mode=false lets the bots join without licensed accounts.
online-mode=false
server-port=25565
server-ip=127.0.0.1
gamemode=survival
difficulty=easy
max-players=10
view-distance=8
simulation-distance=8
spawn-protection=0
allow-cheats=true
enable-command-block=false
white-list=false
motd=minecraft-ai-bots local test server
level-name=world
pvp=false
